### PR TITLE
ADD storybook

### PR DESCRIPTION
**Pull request by ndelangen**

### CODE REVIEW

**Comment by davidhund** [comment]
Hi @ndelangen - Thank you for your PR. We've [_just_ discussed adding Storybook](https://github.com/davidhund/styleguide-generators/issues/52)

As SB currently works with a couple of libs/frameworks (React, Vue, etc) my thinking was to introduce a new category 'Multiple' and list the libs as 'tags'. What do you think?

**Comment by ndelangen** [comment]
@davidhund yes, that is actually way better! I was trying to find the proper spot and just settled unto 'NodeJS'. Do you want me to change this PR? Or are you going to merge this and create the category yourself and then move storybook over?

**Comment by longility** [comment]
@ndelangen Thanks for picking this up and doing it. I was gonna do it, but man time has been limited for me.

**Comment by ndelangen** [comment]
I'm on it!

**Comment by ndelangen** [comment]
Good to go like this?

**Comment by davidhund** [comment]
Thank you @ndelangen!

**Pull request merged**
