### PR TITLE
Add articles about UI components & workflow

### PR DESCRIPTION
**Pull request by domyen**

### CODE REVIEW

**Comment by davidhund** [comment]
Thanks for your contribution @domyen!

I’m going to be honest here and say that I’m a little bit hesitant to add your articles for two reasons:

- They are very specific to a _small subset_ of the topic of this list: component driven design of JS view-libraries (specifically React, with Storybook and your app)
- Since all articles are quite clearly written in the context of the development of Chromatic’s app, it could come across as a little bit spammy

I‘ve read the articles and it seems everybody at Chromatic is really passionate about Component Driven Design. I am in no way dismissing your expertise- and work in this area and it is not my intention disrespect you, but I am a bit conflicted in this.

I'll have a think on it and would love feedback.

🖖🏻

**Comment by domyen** [comment]
Thanks for checking it out David! I really appreciate the way you articulated your feedback.

The perspective of the articles is that UI components are the basic building blocks of styleguides/pattern libs/design systems. As such, the writing walks through the tools and tactics (with code examples) for actually building a pattern library from the ground up. I figured showing folks how to go from UI component -> pattern library would illustrate that it's not hard to get started.

I hope you'll consider including one of them. 👍

(p.s., Sorry to come across as spammy. The articles on Chroma were written long before Chromatic started, there aren't any sneaky sales CTAs hidden there. )

**Comment by davidhund** [comment]
Thanks for your reply @domyen.

How about adding the article on a [UI Component Playbook](https://blog.hichroma.com/ui-component-playbook-fd3022d00590)?

It offers very helpful background information and practical guidelines to get started (kudos b.t.w. 👏) and also links back to the other articles you mentioned.

**Comment by domyen** [comment]
Sounds good! Updated the PR to reflect your suggestion.

**Pull request merged**
